blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/sheikhhaziq/gyawun_music/discussions
    about: Please use Discussions for questions and general support.
